name: Solar System Workflow

on: 
    workflow_dispatch: 
    push: 
        branches: 
            - main
            - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    
jobs:
    unit_testing:
        strategy:
            matrix:
              os: [ubuntu-latest, macos-latest]
              nodejs_version: [18,20]
              exclude:
                - nodejs_version: 18
                  os: macos-latest
        name: Unit Testing
        runs-on: ${{ matrix.os }}
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
    
        - name: Setup NodeJs Version - ${{ matrix.nodejs_version }}
          uses: actions/setup-node@v3
          with:
              node-version: ${{ matrix.nodejs_version }}

        - name: Caching NPM dependencies
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}

        - name: Install Dependencies
          run: npm install

        - name: Unit Testing
          id: node-js-testing-step
          run: npm test

        - name: Archive test file
          # if: failure() && steps.node-js-testing-step.outcome == 'failure' || steps.node-js-testing-step.outcome == 'success' ##
          if: always()
          uses: actions/upload-artifact@v3
          with:
           name: Unittest-result
           path: test-results.xml

    code_coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Setup NodeJs Version - 18
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Caching NPM dependencies
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}

        - name: Install Dependencies
          run: npm install

        - name: Coverage Testing
          continue-on-error: true
          run: npm run coverage

        - name: Code coverage test
          uses: actions/upload-artifact@v3
          with:
            name: codecoverage-result
            path: coverage
            retention-days: 2

    docker:
        needs: [unit_testing, code_coverage]
        runs-on: ubuntu-latest
        name: Login into docker
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{vars.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}