name: Solar System Workflow

on: 
    workflow_dispatch: 
    push: 
        branches: 
            - main
            - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    
jobs:
    unit_testing:
        strategy:
            matrix:
              os: [ubuntu-latest, macos-latest]
              nodejs_version: [18,19,20]
              exclude:
                - nodejs_version: 18
                  os: macos-latest
        name: Unit Testing
        runs-on: ${{ matrix.os }}
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
    
        - name: Setup NodeJs Version - ${{ matrix.nodejs_version }}
          uses: actions/setup-node@v3
          with:
              node-version: ${{ matrix.nodejs_version }}

        - name: Install Dependencies
          run: npm install

        - name: Unit Testing
          run: npm test

        - name: Archive test file
          uses: actions/upload-artifact@v3
          with:
           name: Unit test result
           path: test-results.xml